spring:
  application:
    name: swe-agent
  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY}
      chat:
        options:
          model: llama-3.3-70b-versatile
    mcp:
      client:
        enabled: true
        type: sync
        request-timeout: 180s
        sse:
          connections:
            tools:
              url: http://localhost:8081
              request-timeout: 180s
        streamable-http:
          connections:
            tools:
              url: http://localhost:8081
              request-timeout: 180s
server:
  port: 8080
