server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


spring:
  application:
    name: swe-agent-mcp-tools
  ai:
    mcp:
      server:
        name: swe-agent-mcp-tools
        version: 1.0.0
        protocol: STREAMABLE
